### ISSUE TITLE
[Bug]: When export from web, the values are saving in firebase as int, that's why when import in android, getting error. in android data are saving as double that creates no issue. hope you understand.

### ISSUE THREAD

**Issue by RahajulAminRaju** [hm21/pro_image_editor#221]
### Package Version

5.2.2

### Flutter Version

Flutter 3.26.0-0.1.pre

### Platforms

Android, Web

### How to reproduce?

When export from web, the values are saving in firebase as int, that's why when import in android, getting error. in android data are saving as double that creates no issue. hope you understand.

### Logs (optional)

```sh
======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Builder(dirty, dependencies: [MediaQuery]):
type 'int' is not a subtype of type 'double'

The relevant error-causing widget was: 
  MaterialApp MaterialApp:file:///D:/Company%20Projects/Flutter%20Projects/Thumbnail-Maker-Repo/Thumbnail%20Maker/thumbnailmaker/lib/main.dart:35:12
When the exception was thrown, this was the stack: 
#0      new Layer.fromMap (package:pro_image_editor/models/layer/layer.dart:52:31)
#1      new ImportStateHistory.fromMap (package:pro_image_editor/models/import_export/import_state_history.dart:61:26)
#2      new ImportStateHistory.fromJson (package:pro_image_editor/models/import_export/import_state_history.dart:119:31)
#3      _EditPageAdminState._openEditor.<anonymous closure> (package:thumbnailmaker/admin/edit_page_admin.dart:214:52)
#4      MaterialPageRoute.buildContent (package:flutter/src/material/page.dart:53:55)
#5      MaterialRouteTransitionMixin.buildPage (package:flutter/src/material/page.dart:111:27)
#6      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:1107:53)
#7      Builder.build (package:flutter/src/widgets/basic.dart:7716:48)
#8      StatelessElement.build (package:flutter/src/widgets/framework.dart:5707:49)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:15)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5619:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5613:5)
...     Normal element mounting (219 frames)
#231    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4488:16)
#232    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7055:36)
#233    Element.updateChild (package:flutter/src/widgets/framework.dart:3971:18)
#234    Element.updateChildren (package:flutter/src/widgets/framework.dart:4158:32)
#235    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7080:17)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5662:16)
#238    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
```

**Comment by hm21** [comment]
Any 'number' value, such as int or double, is stored as number in Firebase. The issue you're encountering is that if you save a double, like 1.0, it will be stored as 1 in Firebase. When accessed via the web, this won't cause problems because JavaScript treats both int and double as number. However, on Dart's native platforms, this can lead to issues when the type changes unexpectedly.

However, I have released version `5.2.3`, which should resolve the issue by ensuring that the type is correct, even if the type has changed. If you wish to use an older version of the editor, you will need to handle this manually before importing it into the editor. In such cases, you must verify each value to ensure the type is correct, and if necessary, convert it to the appropriate type.
