### ISSUE TITLE
[Bug]: Throw exception when i trying add new photo layer

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#77]
### Package Version

3.0.8

### Flutter Version

3.22.1

### Platforms

Android, iOS

### How to reproduce?

I'm trying to add a new photo layer as a sticker, but it throws an exception. I was working on version 3.0.5. I think it happens from version 3.0.6 after you call setState when adding a new layer from an external source

### Logs (optional)

```sh
======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/box.dart': Failed assertion: line 327 pos 12: 'width > 0.0': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  FittedBox FittedBox:file:///Users/thanglq/Downloads/pro_image_editor-stable%202/lib/widgets/layer_widget.dart:369:14
When the exception was thrown, this was the stack: 
#2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:327:12)
#3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2727:30)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#5      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:280:14)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#7      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2715:14)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:2577:7)
#9      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:239:12)
```

### Example code (optional)

```Dart
Future<void> _pickImage() async {
    final picker = ImagePicker();
    final pickedFile = await picker.pickImage(source: ImageSource.gallery);

    if (pickedFile == null) return;

    final imagePath = pickedFile.path;

    editorKey.currentState?.addLayer(
      StickerLayerData(
        offset: const Offset(0, 0),
        sticker: Image.file(File(imagePath)),
      ),
    );
  }
```

**Comment by hm21** [comment]
The problem is that you are inserting a layer that has no size. This happens because your image is not completely loaded when you insert it. Before was an issue that I didn't call setState, so your image had time to load completely until some interactions happen which will call `setState`. 
Anyway, what you need to do is to precache the image, like in the example [here](https://github.com/hm21/pro_image_editor/blob/49bc149cd6918ecb58fa2901d09d38de67c213be/example/lib/pages/movable_background_image.dart#L61-L94). I also recommend you to decode the image that you can also add the width and height to the image like in the example, even this step is not required.

**Comment by thanglq1** [comment]
I got it. Thank you.
